version: "3.7"

services:
    api:
        build: .
        container_name: eu_militar_api_prod
        command: yarn start
        restart: on-failure
        ports:
            - 80:22000
        depends_on:
            - db
        environment:
            PORT: 22000
            DB_NAME: nice_marmot
            DB_USER: user
            DB_PASS: password
            DB_HOST: db
            DB_PORT: 3306

    db:
        image: mariadb
        restart: on-failure
        container_name: eu_militar_database_prod
        volumes: 
            - ~/.data/eu-militar/mysql:/var/lib/mysql:z
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: nice_marmot
            MYSQL_ROOT_PASSWORD: passwd

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        container_name: eu_militar_phpmyadmin_prod
        ports:
            - 8080:80
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: nice_marmot
            MYSQL_ROOT_PASSWORD: passwd
            PMA_HOST: db
