FROM node
WORKDIR /usr/share/api
RUN mkdir dist
COPY . .
RUN yarn install && yarn global add vercel typescript && \
    useradd api -ms /bin/bash && \
    chown -R api:api .
USER api
CMD [ "yarn", "run", "dev" ]
ENV PATH ${PATH}:/usr/share/api/node_modules/.bin