version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: eu_militar_api
        restart: on-failure
        volumes:
            - ./:/usr/share/api:z
        env_file: .env
        user: root
        ports:
            - 80:22000
        depends_on:
            - db
        environment:
            PORT: 22000
            DB_NAME: nice_marmot
            DB_USER: user
            DB_PASS: password
            DB_HOST: db
            DB_PORT: 3306
            CORS: '*'

    db:
        image: mariadb
        restart: on-failure
        container_name: eu_militar_database
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: nice_marmot
            MYSQL_ROOT_PASSWORD: passwd

    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        container_name: eu_militar_phpmyadmin
        ports:
            - 8080:80
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: nice_marmot
            MYSQL_ROOT_PASSWORD: passwd
            PMA_HOST: db
