FROM node:14.16.0
WORKDIR /usr/share/api
RUN mkdir dist; mkdir /usr/share/logs
COPY . .
RUN yarn install && \
    useradd api -ms /bin/bash && \
    chown -R api:api .
USER api
CMD [ "yarn", "run", "dev" ]
ENV PATH ${PATH}:/usr/share/api/node_modules/.bin