version: "3.7"

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: on-failure
        volumes:
            - ./:/usr/share/api:z
        user: root
        ports:
            - 80:22000
            - 9229:9229
        depends_on:
            - db
            - test_db
        environment:
            PORT: 22000
            DB_NAME: eumili89_portal_aluno
            DB_USER: user
            DB_PASS: password
            DB_HOST: db
            DB_PORT: 3306
            TEST_DB_NAME: eumili89_portal_aluno
            TEST_DB_USER: user
            TEST_DB_PASS: password
            TEST_DB_HOST: test_db
            TEST_DB_PORT: 3306
            CORS: '*'
            EXPIRATION_TIME: 48

    db:
        image: mysql:5.7
        restart: on-failure
        volumes:
            - eu-militar:/var/lib/mysql
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: eumili89_portal_aluno
            MYSQL_ROOT_PASSWORD: passwd
    
    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: eumili89_portal_aluno
            MYSQL_ROOT_PASSWORD: passwd
            PMA_HOST: db

    test_db:
        image: mysql:5.7
        restart: on-failure
        volumes:
            - eu-militar-test:/var/lib/mysql
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: eumili89_portal_aluno
            MYSQL_ROOT_PASSWORD: passwd

    test_phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        depends_on:
            - test_db
        ports:
            - 8082:80
        environment:
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            MYSQL_DATABASE: eumili89_portal_aluno
            MYSQL_ROOT_PASSWORD: passwd
            PMA_HOST: test_db

volumes: 
    eu-militar:
    eu-militar-test: